name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-18.04
    steps:
      - name: ssh into droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: 80
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          script: |
            whoami
